### ISSUE TITLE
代码怎么使用？

### ISSUE THREAD

**Issue by IamMegatron2025** [MedusaLeee/ContinuousSpeechRecognition#1]
您好，代码怎么使用啊。可以给点使用说明吗？
谢谢！

**Comment by MedusaLeee** [comment]
您好，长语音识别，现在讯飞已经有 语音转写了，所以可以不用语音听写API来实现长语音听写了，您来的刚刚好，我刚做完 语音转写的调研。给您个地址吧https://www.xfyun.cn/services/lfasr

**Comment by MedusaLeee** [comment]
@IvyGongoogle 如果您还有其他问题可以留言交流。

**Comment by IamMegatron2025** [comment]
@MedusaLeee  您好，抱歉 回复晚了。 谢谢您的回复，有问题我再留言。
