### ISSUE TITLE
<其他错误------------: 11201> is caused by what?

### ISSUE THREAD

**Issue by zxy-bjtu** [MedusaLeee/ContinuousSpeechRecognition#2]

**Comment by MedusaLeee** [comment]
@zhangxinyun15281253  “ 11201”是 讯飞的 sdk 抛出的 错误，这个代码 版本很老了，也需要自己去申请 appId，我代码里的appId肯定过期了，现在 讯飞支持 语音转写了，你可以去看看 https://www.xfyun.cn/services/lfasr，如果还有问题, 还可以继续在这提问

**Comment by MedusaLeee** [comment]
此issues 我先关闭了，如果还有问题 欢迎提问
